### ISSUE TITLE
Defining variables doesn't like newlines.

### ISSUE THREAD

**Issue by Steve0Greatness** [MystPi/bella#2]
I get this error on `countdown.bella` in the examples directory.
```
✕ error: invalid syntax
  ┌─ ./examples/countdown.bella:1:16
  │
1 │ let countdown =
  │                ~
  │

? I don't understand what this means
```

**Comment by MystPi** [comment]
That's weird—it works on my machine. I'll check it out; thanks for the report!

**Comment by MystPi** [comment]
Did you modify the file at all? Maybe the line endings are messed up.

**Comment by MystPi** [comment]
Yup, it doesn't understand CRLF correctly ATM. I'll push a fix as soon as possible.

**Comment by MystPi** [comment]
It should work now in the latest build. Do you mind testing it out?
