### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by GenericProgrammer1234** [MystPi/bella#5]
A clear reference helps so please. The examples are alright but they don't give me a picture of everything I can do.

**Comment by MystPi** [comment]
I agree, docs would be very helpful. I hope to write them at some point, but not really sure when I'll have the time/dedication to.

**Comment by GenericProgrammer1234** [comment]
I could write documentation assuming everything that you can do is shown in the examples?

**Comment by MystPi** [comment]
I would prefer to write the docs myself as I'm not sure how complete the examples are, especially for some little nuances in the language.

**Comment by GenericProgrammer1234** [comment]
Okay! I could help with formatting though.

**Comment by MystPi** [comment]
I just wrote some basic documentation if you want to take a look. It lives in the [docs](https://github.com/MystPi/bella/tree/main/docs) folder.

**Comment by GenericProgrammer1234** [comment]
Okay the documentation is well written but there is just one thing, this is kinda a nit but immutible should be immutable.

**Comment by MystPi** [comment]
Thank you for the heads up! I wrote the docs in my code editor without spellcheck, and we all know how that turns out. :P
